import {Bone,Box3,BufferGeometry,CanvasTexture,Color,DoubleSide,Float32BufferAttribute,Group,Mesh,MeshPhysicalMaterial,MeshStandardMaterial,RepeatWrapping,Raycaster,SphereGeometry,SRGBColorSpace,TorusGeometry,Uint16BufferAttribute,Vector3} from 'three'
import type {SpeciesId} from './world'

const random=(i:number)=>{const n=Math.sin(i*127.1+19.7)*43758.5453;return n-Math.floor(n)}
const bumpCache=new Map<string,CanvasTexture>()
function coatBump(skin:boolean){const key=skin?'skin':'fur';if(bumpCache.has(key))return bumpCache.get(key)!;const c=document.createElement('canvas');c.width=c.height=512;const g=c.getContext('2d')!;g.fillStyle='#888';g.fillRect(0,0,512,512);for(let i=0;i<14000;i++){const x=random(i)*512,y=random(i+15000)*512,shade=70+random(i+30000)*100;g.strokeStyle=`rgb(${shade},${shade},${shade})`;g.lineWidth=skin?.5:.7;g.beginPath();g.moveTo(x,y);g.lineTo(x+(skin?5:1),y+(skin?Math.sin(x)*3:5+random(i)*9));g.stroke()}const t=new CanvasTexture(c);t.wrapS=t.wrapT=RepeatWrapping;t.repeat.set(skin?3:5,skin?3:5);bumpCache.set(key,t);return t}
export function detailedMaterial(original:MeshStandardMaterial,id:SpeciesId){const material=original.clone(),name=original.name.toLowerCase(),skin=id==='elephant'||id==='hippo',hard=/eye|nose|claw|hoof|ivory|horn/.test(name);material.roughness=hard?.4:skin?.8:.92;material.metalness=0;if(hard){material.map=null;if(/nose|hoof/.test(name))material.color.set('#29231f')}else {material.bumpMap=["flamingo","parrot","peacock"].includes(id)?featherVeins():coatBump(skin);material.bumpScale=skin?.018:.007}return material}

// 从原资产真实的双眼网格分别取左右包围盒，避免把眼睛硬贴到统一模板坐标。
export function eyeAnchors(scene:Group){const boxes=[new Box3(),new Box3()];scene.traverse(o=>{if(!(o instanceof Mesh))return;const material=Array.isArray(o.material)?o.material[0]:o.material;if(!/eye/i.test(material.name))return;const p=o.geometry.getAttribute('position');for(let i=0;i<p.count;i++){const v=new Vector3().fromBufferAttribute(p,i).applyMatrix4(o.matrixWorld);boxes[v.x<0?0:1].expandByPoint(v)}});return boxes.filter(b=>!b.isEmpty()).map(b=>({center:b.getCenter(new Vector3()),size:b.getSize(new Vector3())}))}
const irisColors:Record<SpeciesId,string>={lion:'#c2933a',tiger:'#bcb170',elephant:'#72523a',giraffe:'#604028',zebra:'#634831',panda:'#625344',kangaroo:'#785c37',flamingo:'#e7c783',deer:'#785539',peacock:'#754f31',parrot:'#e8d48c',hippo:'#7a5842'}
export function addEyes(head:Bone,scene:Group,id:SpeciesId){const anchors=eyeAnchors(scene),surfaces:Mesh[]=[];scene.traverse(o=>{if(o instanceof Mesh&&!/eye/i.test((Array.isArray(o.material)?o.material[0]:o.material).name))surfaces.push(o)});const globeMat=new MeshPhysicalMaterial({color:'#28231b',roughness:.12,clearcoat:1,clearcoatRoughness:.03}),rimMat=new MeshStandardMaterial({color:id==='panda'?'#171512':'#493a2c',roughness:.8});anchors.forEach(({center,size})=>{const radius=Math.max(.011,Math.min(.09,Math.max(size.y,size.z)*.64)),eye=new Group(),outward=new Vector3(Math.sign(center.x)*.87,.04,.49).normalize();const ray=new Raycaster(center.clone().addScaledVector(outward,3),outward.clone().negate(),0,4);const surface=ray.intersectObjects(surfaces,false)[0];eye.position.copy(surface?.point??center).addScaledVector(outward,radius*.38).sub(head.position);eye.quaternion.setFromUnitVectors(new Vector3(0,0,1),outward);head.add(eye)
 const globe=new Mesh(new SphereGeometry(radius,24,18),globeMat);globe.scale.set(1,.85,.75);eye.add(globe)
 const iris=new Mesh(new SphereGeometry(radius*.69,24,16),new MeshPhysicalMaterial({color:irisColors[id],roughness:.22,clearcoat:1}));iris.scale.set(1,1,.18);iris.position.z=radius*.65;eye.add(iris)
 const pupil=new Mesh(new SphereGeometry(radius*.37,20,16),new MeshPhysicalMaterial({color:'#080908',roughness:.04,clearcoat:1}));pupil.scale.set(1,1,.17);pupil.position.z=radius*.78;eye.add(pupil)
 const rim=new Mesh(new TorusGeometry(radius*.97,radius*.1,8,32),rimMat);rim.scale.y=.85;eye.add(rim)
 const glint=new Mesh(new SphereGeometry(radius*.12,12,8),new MeshStandardMaterial({color:'#fff9e4',emissive:'#dce8e8',emissiveIntensity:.45,roughness:.1}));glint.position.set(-radius*.22,radius*.23,radius*.82);eye.add(glint)
 });return anchors.length}

export function addWhiskers(head:Bone,scene:Group,id:SpeciesId){if(!['lion','tiger','panda','hippo'].includes(id))return;let nose:Vector3|undefined;scene.traverse(o=>{if(!(o instanceof Mesh))return;const material=Array.isArray(o.material)?o.material[0]:o.material;if(/nose/i.test(material.name))nose=new Box3().setFromObject(o).getCenter(new Vector3())});if(!nose)return;const group=new Group();group.position.copy(nose).sub(head.position);const pos:number[]=[];for(const side of [-1,1])for(let j=0;j<7;j++){const length=id==='panda'?.13:.24,a=new Vector3(side*.035,(j-3)*.008,-.012),b=new Vector3(side*length,(j-3)*.021,.015),c=b.clone().add(new Vector3(0,.0015,0));pos.push(...a.toArray(),...b.toArray(),...c.toArray())}const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(pos,3));g.computeVertexNormals();group.add(new Mesh(g,new MeshStandardMaterial({color:'#d9cbb0',side:DoubleSide,roughness:.85})));head.add(group)}

// 短绒毛沿表面法线生长，复制原网格的蒙皮权重，随身体与鬃毛骨骼一起运动。
export function furGeometry(source:BufferGeometry,id:SpeciesId,materialName:string){if(['elephant','hippo','flamingo','parrot','peacock'].includes(id)||/eye|nose|hoof|claw|horn/i.test(materialName))return null;const p=source.getAttribute('position'),n=source.getAttribute('normal'),si=source.getAttribute('skinIndex'),sw=source.getAttribute('skinWeight');if(!n)return null;const positions:number[]=[],normals:number[]=[],indices:number[]=[],weights:number[]=[],colors:number[]=[],count=/mane/i.test(materialName)?4500:1100,length=/mane/i.test(materialName)?.055:id==='panda'?.018:.012;for(let i=0;i<count;i++){const k=Math.floor(random(i+3)*p.count),v=new Vector3().fromBufferAttribute(p,k),normal=new Vector3().fromBufferAttribute(n,k).normalize();if(v.y<.13)continue;const tangent=new Vector3(normal.z,0,-normal.x).normalize().multiplyScalar(length*.14),tip=v.clone().addScaledVector(normal,length*(.5+random(i+8000)));for(const q of [v.clone().add(tangent),v.clone().sub(tangent),tip]){positions.push(...q.toArray());normals.push(...normal.toArray());indices.push(si.getX(k),si.getY(k),si.getZ(k),si.getW(k));weights.push(sw.getX(k),sw.getY(k),sw.getZ(k),sw.getW(k));const color=new Color().setScalar(.65+random(i+6000)*.35);colors.push(color.r,color.g,color.b)}}const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(positions,3));g.setAttribute('normal',new Float32BufferAttribute(normals,3));g.setAttribute('skinIndex',new Uint16BufferAttribute(indices,4));g.setAttribute('skinWeight',new Float32BufferAttribute(weights,4));g.setAttribute('color',new Float32BufferAttribute(colors,3));return g}

export function featherVeins(){const c=document.createElement('canvas');c.width=c.height=128;const g=c.getContext('2d')!;g.fillStyle='#777';g.fillRect(0,0,128,128);g.strokeStyle='#aaa';g.lineWidth=1;for(let i=-128;i<256;i+=5){g.beginPath();g.moveTo(64,i);g.lineTo(0,i-26);g.moveTo(64,i);g.lineTo(128,i-26);g.stroke()}const t=new CanvasTexture(c);t.colorSpace=SRGBColorSpace;t.wrapS=t.wrapT=RepeatWrapping;t.repeat.set(4,4);return t}
