import {useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {Camera,Plane,Raycaster,Vector2,Vector3} from 'three'
import type {OrbitControls} from 'three-stdlib'
import ZooScene,{type CameraCommand,type CameraSnapshot} from './ZooScene'
import Minimap from './Minimap'
import {beginCarry,cancelCarry,createWorld,info,relocateAnimal,terrainHeight,type Point} from './zoo'
type Grab={id:string;origin:Point;penId:string;startX:number;startY:number;active:boolean;clickCarry:boolean}
export default function App(){const world=useMemo(()=>createWorld(),[]),[selected,setSelected]=useState<string|null>(null),[command,setCommand]=useState<CameraCommand>({id:0,mode:'overview'}),[camera,setCamera]=useState<CameraSnapshot>({x:138,z:155,tx:0,tz:0,distance:248}),[carrying,setCarrying]=useState(false),[help,setHelp]=useState(false),[collapsed,setCollapsed]=useState(false),[toast,setToast]=useState(''),[sound,setSound]=useState(false),[,render]=useState(0),scene=useRef<{camera:Camera;canvas:HTMLCanvasElement;controls:OrbitControls}|null>(null),grab=useRef<Grab|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),audio=useRef<AudioContext|null>(null)
 const notify=useCallback((text:string)=>{setToast(text);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(''),4000)},[])
 const focus=useCallback((id:string)=>{setSelected(id);setCommand(c=>({id:c.id+1,mode:'focus',animalId:id}))},[])
 const ready=useCallback((camera:Camera,canvas:HTMLCanvasElement,controls:OrbitControls)=>{scene.current={camera,canvas,controls}},[])
 const finish=useCallback((cancel=false)=>{const g=grab.current;if(!g)return;const a=world.animals.find(a=>a.id===g.id)!;if(g.active){if(cancel||!relocateAnimal(world,g.id,a.pos)){cancelCarry(world,g.id,g.origin,g.penId);notify(cancel?'已取消搬迁':'请放入围栏内的可站立区域，动物已返回原处')}else notify(`${info[a.species].name}已放入新展区`)}grab.current=null;setCarrying(false);if(scene.current)scene.current.controls.enabled=true},[world,notify])
 const down=useCallback((id:string,e:PointerEvent)=>{if(e.button!==0||grab.current?.clickCarry)return;setSelected(id);const a=world.animals.find(a=>a.id===id)!;grab.current={id,origin:{...a.pos},penId:a.penId,startX:e.clientX,startY:e.clientY,active:false,clickCarry:false};if(scene.current)scene.current.controls.enabled=false},[world])
 useEffect(()=>{const move=(e:PointerEvent)=>{const g=grab.current,s=scene.current;if(!g||!s||e.target!==s.canvas)return;if(!g.active&&Math.hypot(e.clientX-g.startX,e.clientY-g.startY)>5){g.active=beginCarry(world,g.id);setCarrying(g.active)}if(!g.active)return;const rect=s.canvas.getBoundingClientRect(),ray=new Raycaster();ray.setFromCamera(new Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),s.camera);const hit=new Vector3(),plane=new Plane(new Vector3(0,1,0),0);if(ray.ray.intersectPlane(plane,hit)){plane.constant=-terrainHeight(hit.x,hit.z);ray.ray.intersectPlane(plane,hit);if(Math.abs(hit.x)<130&&Math.abs(hit.z)<130)world.animals.find(a=>a.id===g.id)!.pos={x:hit.x,z:hit.z}}},up=(e:PointerEvent)=>{if(grab.current?.active&&e.button===0&&e.target===scene.current?.canvas)move(e);if(grab.current&&!grab.current.clickCarry&&e.button===0)finish();else if(grab.current?.clickCarry&&e.button===0&&e.target===scene.current?.canvas)finish()},key=(e:KeyboardEvent)=>{if(e.key==='Escape'){finish(true);setHelp(false)}if(e.code==='Space'&&e.target===document.body){e.preventDefault();world.paused=!world.paused;render(n=>n+1)}};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);window.addEventListener('keydown',key);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('keydown',key)}},[world,finish])
 useEffect(()=>{const id=setInterval(()=>render(n=>n+1),250);return()=>{clearInterval(id);if(timer.current)clearTimeout(timer.current);audio.current?.close()}},[])
 const startCarry=()=>{if(carrying){finish();return}const a=world.animals.find(a=>a.id===selected);if(!a)return;if(beginCarry(world,a.id)){grab.current={id:a.id,origin:{...a.pos},penId:a.penId,startX:0,startY:0,active:true,clickCarry:true};setCarrying(true);notify('WASD / 方向键或鼠标中键移动镜头，滚轮缩放；左键放下，Esc 取消')}}
 const toggleSound=()=>{if(sound){audio.current?.suspend();setSound(false);return}if(!audio.current){const ctx=new AudioContext(),buffer=ctx.createBuffer(1,ctx.sampleRate*3,ctx.sampleRate),data=buffer.getChannelData(0);let last=0;for(let i=0;i<data.length;i++){last=(last+(Math.random()*2-1)*.02)/1.02;data[i]=last*3}const source=ctx.createBufferSource();source.buffer=buffer;source.loop=true;const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=800;const gain=ctx.createGain();gain.gain.value=.1;source.connect(filter).connect(gain).connect(ctx.destination);source.start();audio.current=ctx}audio.current.resume();setSound(true)}
 const a=world.animals.find(a=>a.id===selected),event=world.events.filter(e=>e.kind==='fight').at(-1)
 return <main className={carrying?'app carrying':'app'}><ZooScene world={world} selected={selected} command={command} carrying={carrying} onAnimalDown={down} onFocus={focus} onReady={ready} onCamera={setCamera}/><div className="brand"><span className="brand-mark">憩</span><div><h1>好吃懒做动物园</h1><p>SLOW DAYS · WILD LIVES</p></div></div><div className="park-status"><span className="live-dot"/>{world.paused?'时间已暂停':'自由生活中'}<span>12 种动物 · 53 位居民</span></div><Minimap world={world} camera={camera} selected={selected}/>{event&&<div className="event-toast" role="status"><span>◇</span>{event.text}<button onClick={()=>setCommand(c=>({id:c.id+1,mode:'map',point:event.pos}))}>查看 →</button></div>}{toast&&<div className="toast" role="status">{toast}</div>}<div className={`toolbar ${collapsed?'collapsed':''}`}><button className="toolbar-toggle" onClick={()=>setCollapsed(!collapsed)} title={collapsed?'展开操作栏':'收起操作栏'}>{collapsed?'⌃':'⌄'}</button>{!collapsed&&<><div className="selection"><small>{carrying?'正在搬迁':'当前观察'}</small><strong>{a?`${info[a.species].name} ${a.id.split('-').at(-1)}`:'整座动物园'}</strong></div><div className="toolbar-divider"/><button onClick={()=>setCommand(c=>({id:c.id+1,mode:'overview'}))}>⌂<span>全园</span></button><button onClick={()=>setCommand(c=>({id:c.id+1,mode:'entrance'}))}>♜<span>大门</span></button><button disabled={!selected} onClick={()=>selected&&focus(selected)}>◎<span>近看</span></button><button disabled={!selected} className={carrying?'active':''} onClick={startCarry}>↟<span>{carrying?'放下':'抓取'}</span></button><button className={world.paused?'active':''} onClick={()=>{world.paused=!world.paused;render(n=>n+1)}}>{world.paused?'▷':'Ⅱ'}<span>{world.paused?'继续':'暂停'}</span></button><button className={sound?'active':''} onClick={toggleSound}>♪<span>环境声</span></button><button onClick={()=>setHelp(!help)}>？<span>操作</span></button></>}</div><div className="gesture-hint">WASD / 方向键移动 · 左键环视 · 滚轮缩放</div>{help&&<div className="help-scrim" onClick={()=>setHelp(false)}><section className="help" onClick={e=>e.stopPropagation()}><button className="help-close" onClick={()=>setHelp(false)}>×</button><small>EXPLORE AT YOUR OWN PACE</small><h2>走进动物的日常</h2><p>W / ↑ 前进，S / ↓ 后退，A / ← 左移，D / → 右移，方向跟随当前视线。鼠标左键拖动旋转视角，滚轮缩放，右键或中键拖动平移。小地图只供查看。</p><p>点击动物选中，双击近看。按住动物拖动即可搬迁；也可以点「抓取」，用 WASD / 方向键或中键移动到新展区，再左键点击地面放下。</p><p>不同动物混养后会自行警戒、追逐或打架。再次抓起动物会中断冲突。饲养员按新住户的食谱补充食物。</p><footer>空格 暂停 / 继续 <span>Esc 取消搬迁</span></footer></section></div>}</main>
}
