import {useMemo} from 'react'
import {useGLTF} from '@react-three/drei'
import {modelUrl} from './modelUrl'
import {CanvasTexture,Color,DoubleSide,Matrix4,Mesh,MeshStandardMaterial,Object3D,PlaneGeometry,SRGBColorSpace,Float32BufferAttribute} from 'three'
import {mergeGeometries} from 'three/examples/jsm/utils/BufferGeometryUtils.js'
type TreeInstance={position:[number,number,number];scale:[number,number,number];rotation?:[number,number,number]}
const rand=(n:number)=>{const v=Math.sin(n*127.1)*43758.5453;return v-Math.floor(v)}
function leafMaterial(){const c=document.createElement('canvas');c.width=128;c.height=64;const g=c.getContext('2d')!;const gradient=g.createLinearGradient(0,0,128,64);gradient.addColorStop(0,'#758c47');gradient.addColorStop(.5,'#9ba767');gradient.addColorStop(1,'#435e33');g.fillStyle=gradient;g.beginPath();g.moveTo(2,32);g.bezierCurveTo(30,-4,100,0,126,32);g.bezierCurveTo(90,66,28,63,2,32);g.fill();g.strokeStyle='#b9b58099';g.lineWidth=1;g.beginPath();g.moveTo(0,32);g.lineTo(126,32);for(let i=20;i<115;i+=14){g.moveTo(i,32);g.lineTo(i+12,12);g.moveTo(i,32);g.lineTo(i+12,52)}g.stroke();const texture=new CanvasTexture(c);texture.colorSpace=SRGBColorSpace;return new MeshStandardMaterial({map:texture,alphaTest:.45,side:DoubleSide,roughness:.95,color:'#b3c59b'})}
export default function Foliage({items}:{items:TreeInstance[]}){const {scene}=useGLTF(modelUrl('acacia'),false,false);const data=useMemo(()=>{scene.updateMatrixWorld(true);let trunk:Mesh|null=null;scene.traverse(o=>{if(o instanceof Mesh&&o.name.endsWith('_0'))trunk=o});const planes:PlaneGeometry[]=[];const dummy=new Object3D();for(let i=0;i<1400;i++){const angle=rand(i+4)*Math.PI*2,r=Math.sqrt(rand(i+1401))*4.4,x=Math.cos(angle)*r,z=Math.sin(angle)*r,y=5.6+(rand(i+2804)-.5)*1.5-(r/4.4)**2*.25;const p=new PlaneGeometry(.3+rand(i+4201)*.32,.12+rand(i+5602)*.12);dummy.position.set(x,y,z);dummy.rotation.set((rand(i+7000)-.5)*Math.PI,rand(i+8400)*Math.PI,rand(i+9800)*Math.PI);dummy.updateMatrix();p.applyMatrix4(dummy.matrix);const color=new Color().setHSL(.22+rand(i)*.04,.2+rand(i+1)*.1,.65+rand(i+2)*.2);p.setAttribute('color',new Float32BufferAttribute(Array.from({length:4},()=>[color.r,color.g,color.b]).flat(),3));planes.push(p)}const geometry=mergeGeometries(planes);planes.forEach(p=>p.dispose());const material=leafMaterial();material.vertexColors=true;return {trunk:trunk as Mesh|null,geometry,material}},[scene]);const set=(mesh:import('three').InstancedMesh|null,matrix:Matrix4)=>{if(!mesh)return;const d=new Object3D();items.forEach((item,i)=>{d.position.set(...item.position);d.scale.set(...item.scale);d.rotation.set(...(item.rotation??[0,0,0]));d.updateMatrix();mesh.setMatrixAt(i,d.matrix.clone().multiply(matrix))});mesh.instanceMatrix.needsUpdate=true;mesh.computeBoundingSphere()};return <group>{data.trunk&&<instancedMesh args={[data.trunk.geometry,data.trunk.material,items.length]} castShadow receiveShadow ref={m=>set(m,data.trunk!.matrixWorld)}/>}<instancedMesh args={[data.geometry,data.material,items.length]} castShadow receiveShadow ref={m=>set(m,new Matrix4())}/></group>}
