import {useMemo} from 'react'
import {BufferGeometry,CanvasTexture,Color,DoubleSide,Float32BufferAttribute,MeshStandardMaterial,Object3D,PlaneGeometry,RepeatWrapping,SRGBColorSpace,Vector3} from 'three'
import Foliage from './Foliage'
import Entrance,{Sign} from './Entrance'
import {baseHeight,pens,roadPoint,terrainHeight,waters,type Point} from './world'
const noise=(n:number)=>{const x=Math.sin(n*127.1+311.7)*43758.5453;return x-Math.floor(x)}
function groundTexture(){const c=document.createElement('canvas');c.width=c.height=512;const g=c.getContext('2d')!;g.fillStyle='#a0a287';g.fillRect(0,0,512,512);for(let i=0;i<55000;i++){const x=noise(i)*512,y=noise(i+60000)*512,n=noise(i+120000);g.fillStyle=n>.65?'rgba(219,208,171,.22)':n>.3?'rgba(73,88,53,.18)':'rgba(63,63,47,.12)';g.fillRect(x,y,noise(i+1)*3+.3,noise(i+2)*2+.3)}const t=new CanvasTexture(c);t.wrapS=t.wrapT=RepeatWrapping;t.repeat.set(75,75);t.colorSpace=SRGBColorSpace;t.anisotropy=8;return t}
function surface(points:Point[],offset:number){
 const cx=points.reduce((s,p)=>s+p.x,0)/points.length,cz=points.reduce((s,p)=>s+p.z,0)/points.length,positions:number[]=[],uv:number[]=[],indices:number[]=[],rings=32,n=points.length
 for(let r=0;r<=rings;r++)for(let k=0;k<n;k++){const t=r/rings,x=cx+(points[k].x-cx)*t,z=cz+(points[k].z-cz)*t;positions.push(x,terrainHeight(x,z)+offset,z);uv.push(x/1800+.5,z/1800+.5)}
 for(let r=0;r<rings;r++)for(let k=0;k<n;k++){const a=r*n+k,b=r*n+(k+1)%n,c=(r+1)*n+k,d=(r+1)*n+(k+1)%n;indices.push(a,c,b,b,c,d)}const g=new BufferGeometry();g.setAttribute('position',new Float32BufferAttribute(positions,3));g.setAttribute('uv',new Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();return g
}
function ribbon(points:Point[],width:number){const pos:number[]=[],uv:number[]=[],indices:number[]=[];let len=0;points.forEach((p,i)=>{const prev=points[Math.max(0,i-1)],next=points[Math.min(points.length-1,i+1)],dx=next.x-prev.x,dz=next.z-prev.z,d=Math.hypot(dx,dz)||1;if(i)len+=Math.hypot(p.x-prev.x,p.z-prev.z);for(const side of [-1,1]){const x=p.x+dz/d*width/2*side,z=p.z-dx/d*width/2*side;pos.push(x,terrainHeight(x,z)+.035,z);uv.push(side===-1?0:1,len/width)}if(i){const k=i*2;indices.push(k-2,k-1,k,k-1,k+1,k)}});const geom=new BufferGeometry();geom.setAttribute('position',new Float32BufferAttribute(pos,3));geom.setAttribute('uv',new Float32BufferAttribute(uv,2));geom.setIndex(indices);geom.computeVertexNormals();return geom}
type Instance={position:[number,number,number];scale:[number,number,number];rotation?:[number,number,number];color?:string}
function Instances({items,kind,material}:{items:Instance[];kind:'sphere'|'cylinder'|'rock'|'grass';material:MeshStandardMaterial}){const transforms=useMemo(()=>{const dummy=new Object3D();return items.map(item=>{dummy.position.set(...item.position);dummy.scale.set(...item.scale);dummy.rotation.set(...(item.rotation??[0,0,0]));dummy.updateMatrix();return dummy.matrix.clone()})},[items]);return <instancedMesh args={[undefined,material,items.length]} castShadow={kind!=='grass'} receiveShadow ref={mesh=>{if(mesh){transforms.forEach((m,i)=>{mesh.setMatrixAt(i,m);if(items[i].color)mesh.setColorAt(i,new Color(items[i].color))});mesh.instanceMatrix.needsUpdate=true;if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true}}}>{kind==='sphere'?<sphereGeometry args={[1,10,8]}/>:kind==='rock'?<dodecahedronGeometry args={[1,1]}/>:kind==='grass'?<planeGeometry args={[1,1]}/>:<cylinderGeometry args={[1,1,1,7]}/>}</instancedMesh>}
export default function Landscape(){
 const data=useMemo(()=>{
  const texture=groundTexture(),ground=new PlaneGeometry(1800,1800,450,450);ground.rotateX(-Math.PI/2);const p=ground.getAttribute('position');for(let i=0;i<p.count;i++)p.setY(i,terrainHeight(p.getX(i),p.getZ(i)));ground.computeVertexNormals()
  const trees:Instance[]=[],leaves:Instance[]=[],trunks:Instance[]=[],rocks:Instance[]=[],posts:Instance[]=[],rails:Instance[]=[],grass:Instance[]=[]
  const tree=(x:number,z:number,seed:number,small=false)=>{if(Math.abs(x-26)<28&&z>99&&z<140)return;const y=terrainHeight(x,z),h=(small?3:4.2)+noise(seed)*2;trees.push({position:[x,y,z],scale:[h/6,h/6,h/6],rotation:[0,noise(seed)*6.28,0]});trunks.push({position:[x,y+h/2,z],scale:[.16,h,.16],color:'#766950'});for(let j=0;j<5;j++){const a=j*2.4,r=1+noise(seed+j),tx=x+Math.cos(a)*r,tz=z+Math.sin(a)*r,ty=y+h-1+noise(seed+j+4)*1.6;const start=new Vector3(x,y+h*.58,z),end=new Vector3(tx,ty,tz),mid=start.clone().lerp(end,.5),dir=end.clone().sub(start);const dummy=new Object3D();dummy.quaternion.setFromUnitVectors(new Vector3(0,1,0),dir.clone().normalize());trunks.push({position:[mid.x,mid.y,mid.z],scale:[.08,dir.length(),.08],rotation:[dummy.rotation.x,dummy.rotation.y,dummy.rotation.z]});for(let k=0;k<4;k++){leaves.push({position:[tx+(noise(seed+j*40+k)-.5)*2,ty+(noise(seed+j*90+k)-.5),tz+(noise(seed+j*70+k)-.5)*2],scale:[1.4+noise(k+seed),.8+noise(k+seed+2)*.8,1.4+noise(k+seed+3)],color:['#566d40','#687b4b','#7c8954','#4d6945'][k]})}}}
  pens.forEach((pen,index)=>{pen.obstacles.forEach((o,k)=>{if(o.rock){rocks.push({position:[o.x,terrainHeight(o.x,o.z)+.7,o.z],scale:[o.radius,1.2,o.radius*.8],rotation:[noise(k),noise(index),.1],color:'#929183'});for(let j=0;j<3;j++)rocks.push({position:[o.x+Math.sin(j*2)*1.3,terrainHeight(o.x,o.z)+.3,o.z+Math.cos(j*2)*1.3],scale:[.7,.5,.7]})}else tree(o.x,o.z,index*31+k)});
   const high=pen.species==='lion'||pen.species==='tiger',height=high?2.6:1.45;pen.points.forEach((pt,i)=>{const next=pen.points[(i+1)%pen.points.length];if(Math.hypot(pt.x-pen.gate.x,pt.z-pen.gate.z)<2.6)return;posts.push({position:[pt.x,terrainHeight(pt.x,pt.z)+height/2,pt.z],scale:[.075,height,.075]});for(const h of [height*.35,height*.94]){const a=new Vector3(pt.x,terrainHeight(pt.x,pt.z)+h,pt.z),b=new Vector3(next.x,terrainHeight(next.x,next.z)+h,next.z),d=b.clone().sub(a),mid=a.clone().lerp(b,.5),dummy=new Object3D();dummy.quaternion.setFromUnitVectors(new Vector3(0,1,0),d.clone().normalize());rails.push({position:[mid.x,mid.y,mid.z],scale:[.035,d.length(),.035],rotation:[dummy.rotation.x,dummy.rotation.y,dummy.rotation.z]})}})
   for(let i=0;i<180;i++){const a=noise(i+index*500)*Math.PI*2,r=.8+noise(i+index*900)*.22,x=pen.center.x+Math.cos(a)*pen.rx*r,z=pen.center.z+Math.sin(a)*pen.rz*r;grass.push({position:[x,terrainHeight(x,z)+.28,z],scale:[.13,.4+noise(i)*.3,1],rotation:[0,noise(i+4)*Math.PI,noise(i)*.3],color:['#748257','#8c9565','#a3a278'][i%3]})}
  })
  for(let i=0;i<95;i++){const a=i*2.39996,r=116+noise(i+4)*50;tree(Math.cos(a)*r,Math.sin(a)*r,i*7,i%4===0)}
  for(let i=0;i<18;i++){const a=i*Math.PI*2/18;tree(Math.sin(a)*37,Math.cos(a)*30,900+i,true)}
  return {texture,ground,trees,leaves,trunks,rocks,posts,rails,grass,roads:[ribbon(Array.from({length:181},(_,i)=>roadPoint(i*Math.PI*2/180)),5),ribbon([{x:26.5,z:39.84},{x:25,z:58},{x:24,z:79},{x:26,z:96},{x:26,z:115}],6),...pens.map(p=>ribbon([roadPoint(p.angle),p.gate],3))],patches:pens.map(p=>surface(p.points,.013)),wood:new MeshStandardMaterial({color:'#796e58',roughness:1}),leaf:new MeshStandardMaterial({color:'white',roughness:.95}),stone:new MeshStandardMaterial({color:'#9c9a8c',roughness:.94}),metal:new MeshStandardMaterial({color:'#4b5149',metalness:.4,roughness:.7}),grassMaterial:new MeshStandardMaterial({color:'white',roughness:1,side:DoubleSide})}
 },[])
 return <group>
  <mesh geometry={data.ground} receiveShadow><meshStandardMaterial color="#899379" map={data.texture} roughness={1}/></mesh>
  {data.patches.map((geom,i)=><mesh geometry={geom} key={pens[i].id} receiveShadow><meshStandardMaterial side={DoubleSide} color={pens[i].color} map={data.texture} roughness={1}/></mesh>)}
  {data.roads.map((geom,i)=><mesh key={i} geometry={geom} receiveShadow><meshStandardMaterial side={DoubleSide} color="#d3c5a7" roughness={.95} map={data.texture} polygonOffset polygonOffsetFactor={-1}/></mesh>)}
  <Foliage items={data.trees}/><Instances items={data.rocks} kind="rock" material={data.stone}/><Instances items={data.posts} kind="cylinder" material={data.metal}/><Instances items={data.rails} kind="cylinder" material={data.metal}/><Instances items={data.grass} kind="grass" material={data.grassMaterial}/>
  {waters.map((w,i)=><group key={i} position={[w.x,w.level,w.z]}><mesh rotation={[-Math.PI/2,0,0]} scale={[w.rx,w.rz,1]} receiveShadow><circleGeometry args={[1,96]}/><meshPhysicalMaterial color="#577e78" roughness={.18} metalness={.25} transparent opacity={.88} clearcoat={1}/></mesh>{Array.from({length:i?14:45},(_,k)=>{const a=k*2.4,x=Math.cos(a)*w.rx*.97,z=Math.sin(a)*w.rz*.97;return <group key={k} position={[x,.1,z]}>{[0,1,2].map(j=><mesh key={j} position={[j*.14,.4,0]} rotation={[.1*j,0,.12*j]}><cylinderGeometry args={[.018,.025,.8+j*.2,4]}/><meshStandardMaterial color="#7e8652"/></mesh>)}</group>})}</group>)}
  {pens.map((p,i)=><group key={p.id}>
   <group position={[p.gate.x,baseHeight(p.gate.x,p.gate.z),p.gate.z]} rotation={[0,p.angle+Math.PI,0]}><mesh position={[0,1.9,0]} castShadow><boxGeometry args={[2.4,.75,.12]}/><meshStandardMaterial color="#444d3e"/></mesh><group position={[0,1.93,.08]}><Sign text={`${String(i+1).padStart(2,'0')} · ${p.species.toUpperCase()}`} width={2.25} height={.5} size={115}/></group>{[-1,1].map(x=><mesh key={x} position={[x,.85,0]}><cylinderGeometry args={[.065,.065,1.7,8]}/><meshStandardMaterial color="#635f4c"/></mesh>)}</group>
   <group position={[p.center.x+Math.cos(p.angle)*8,baseHeight(p.center.x,p.center.z),p.center.z-Math.sin(p.angle)*8]} rotation={[0,p.angle,0]}>{[-2,2].flatMap(x=>[-1.4,1.4].map(z=><mesh key={`${x}-${z}`} position={[x,1.8,z]} castShadow><cylinderGeometry args={[.12,.15,3.6,8]}/><meshStandardMaterial color="#76674e"/></mesh>))}<mesh position={[0,3.6,0]} rotation={[0,0,.07]} castShadow><boxGeometry args={[5,.16,3.8]}/><meshStandardMaterial color="#a39776"/></mesh></group>
   {p.feeders.map((f,k)=><mesh key={k} position={[f.x,terrainHeight(f.x,f.z)+.18,f.z]} receiveShadow><cylinderGeometry args={[.9,.8,.3,20,1,true]}/><meshStandardMaterial color="#756f5c" side={DoubleSide} roughness={.8}/></mesh>)}
  </group>)}
  <Entrance/>
 </group>
}
