import {species,info,pens,penById,penAt,distance,nearestFree,walkable,swimmer,roadPoint,terrainHeight,waterAt,type SpeciesId,type Point,type Diet} from './world'
import {findPath} from './navigation'
export * from './world'
export type AnimalState='roam'|'seek'|'eat'|'rest'|'carried'|'settle'|'alert'|'chase'|'attack'|'flee'|'display'|'fly'
export type Animal={id:string;species:SpeciesId;penId:string;pos:Point;heading:number;state:AnimalState;path:Point[];speed:number;hunger:number;energy:number;timer:number;phase:number;gait:number;scale:number;decision:number;foodId?:string;targetId?:string;cooldown:number;encounter:number;hit:boolean;recoil:number;altitude:number;temper:number}
export type Food={id:string;penId:string;diet:Diet;pos:Point;amount:number;age:number;slots:Record<string,number>}
export type Keeper={id:number;pos:Point;heading:number;state:'walk'|'feed';penIndex:number;route:Point[];timer:number;phase:number}
export type ZooEvent={id:number;pos:Point;text:string;time:number;kind:'fight'|'feed'|'move'}
export type ZooWorld={animals:Animal[];keepers:Keeper[];foods:Food[];events:ZooEvent[];elapsed:number;feedCount:number;transferCount:number;conflictCount:number;paused:boolean;seed:number;carriedId:string|null}
const random=(w:ZooWorld)=>{w.seed=(Math.imul(w.seed,1664525)+1013904223)>>>0;return w.seed/4294967296}
export function createWorld():ZooWorld {
 const w:ZooWorld={animals:[],keepers:[],foods:[],events:[],elapsed:0,feedCount:0,transferCount:0,conflictCount:0,paused:false,seed:314159,carriedId:null}
 for(const s of species){const pen=pens.find(p=>p.species===s.id)!;for(let k=0;k<s.count;k++){const angle=k*2.4,r=4+Math.sqrt(k)*2.9;const pos=nearestFree({x:pen.center.x+Math.cos(angle)*r,z:pen.center.z+Math.sin(angle)*r},pen,s.radius,swimmer(s.id),w.animals.filter(a=>a.penId===pen.id).map(a=>a.pos))??{...pen.center};w.animals.push({id:`${s.id}-${k+1}`,species:s.id,penId:pen.id,pos,heading:random(w)*Math.PI*2,state:'rest',path:[],speed:0,hunger:48+random(w)*30,energy:80,timer:1+k*.7,phase:random(w)*20,gait:random(w)*Math.PI*2,scale:.94+random(w)*.12,decision:random(w),cooldown:0,encounter:0,hit:false,recoil:0,altitude:0,temper:.7+random(w)*.6})}}
 for(let i=0;i<4;i++){const p=pens[i*3];w.keepers.push({id:i,pos:roadPoint(p.angle),heading:p.angle,state:'walk',penIndex:i*3,route:[p.gate],timer:0,phase:0})}return w
}
function event(w:ZooWorld,a:Point,text:string,kind:ZooEvent['kind']){w.events.push({id:Math.floor(w.elapsed*1000)+w.events.length,pos:{...a},text,time:w.elapsed,kind});if(w.events.length>20)w.events.shift()}
function releaseFood(w:ZooWorld,a:Animal){for(const f of w.foods)delete f.slots[a.id];a.foodId=undefined}
function goal(a:Animal,p:Point){const s=info[a.species];a.path=findPath(a.pos,p,penById(a.penId),s.radius*a.scale,swimmer(a.species))}
function wander(w:ZooWorld,a:Animal){const pen=penById(a.penId),s=info[a.species];for(let i=0;i<12;i++){const p={x:pen.center.x+(random(w)-.5)*pen.rx*2,z:pen.center.z+(random(w)-.5)*pen.rz*2};if(walkable(p,pen,s.radius*a.scale,swimmer(a.species))){goal(a,p);if(a.path.length){const flightChance=a.species==='parrot'?.55:a.species==='flamingo'?.24:a.species==='peacock'?.08:0;a.state=flightChance>0&&random(w)<flightChance?'fly':'roam';a.timer=45;return}}}a.state='rest';a.timer=3}
export function beginCarry(w:ZooWorld,id:string){const a=w.animals.find(a=>a.id===id);if(!a||w.carriedId)return false;releaseFood(w,a);a.path=[];a.state='carried';a.speed=0;a.targetId=undefined;w.carriedId=id;for(const b of w.animals)if(b.targetId===id){b.targetId=undefined;b.state='rest';b.timer=2;b.path=[];b.cooldown=5}return true}
export function relocateAnimal(w:ZooWorld,id:string,p:Point){const a=w.animals.find(a=>a.id===id),pen=penAt(p);if(!a||!pen)return false;const s=info[a.species],dest=nearestFree(p,pen,s.radius*a.scale,swimmer(a.species),w.animals.filter(b=>b.penId===pen.id&&b.id!==id).map(b=>b.pos));if(!dest)return false;releaseFood(w,a);a.penId=pen.id;a.pos=dest;a.path=[];a.state='settle';a.timer=1.5;a.cooldown=1.5;a.targetId=undefined;a.altitude=0;w.carriedId=null;w.transferCount++;event(w,dest,`${s.name}已进入${pen.name}`,'move');return true}
export function cancelCarry(w:ZooWorld,id:string,origin:Point,penId:string){const a=w.animals.find(a=>a.id===id);if(!a)return;a.pos={...origin};a.penId=penId;a.state='settle';a.timer=1;a.cooldown=3;a.altitude=0;w.carriedId=null}
const fighting=(a:Animal)=>['alert','chase','attack','flee'].includes(a.state)
function calm(a:Animal){a.state='rest';a.timer=2;a.cooldown=15;a.path=[];a.targetId=undefined;a.encounter=0}
function flee(w:ZooWorld,a:Animal,threat:Animal){releaseFood(w,a);const dx=a.pos.x-threat.pos.x,dz=a.pos.z-threat.pos.z,d=Math.hypot(dx,dz)||1;const dest=nearestFree({x:a.pos.x+dx/d*10,z:a.pos.z+dz/d*10},penById(a.penId),info[a.species].radius*a.scale,swimmer(a.species));a.state='flee';a.targetId=threat.id;a.timer=5;a.encounter=0;if(dest)goal(a,dest)}
export function stepWorld(w:ZooWorld,dt:number){
 if(w.paused)return;dt=Math.min(dt,.1);w.elapsed+=dt
 // 空间分桶只比较同展区近邻，群体规模增加时不进行全场两两碰撞。
 const buckets=new Map<string,Animal[]>(),bucket=(a:Animal,x=0,z=0)=>`${a.penId}:${Math.floor(a.pos.x/10)+x}:${Math.floor(a.pos.z/10)+z}`
 for(const a of w.animals){const k=bucket(a);if(!buckets.has(k))buckets.set(k,[]);buckets.get(k)!.push(a)}
 for(const a of w.animals){a.phase+=dt;a.cooldown=Math.max(0,a.cooldown-dt);a.recoil=Math.max(0,a.recoil-dt);if(a.state==='carried')continue;const s=info[a.species],pen=penById(a.penId),r=s.radius*a.scale;a.hunger=Math.min(100,a.hunger+dt*.045);a.timer-=dt;a.decision-=dt;const near:Animal[]=[];for(let x=-1;x<=1;x++)for(let z=-1;z<=1;z++)near.push(...(buckets.get(bucket(a,x,z))??[]))
 if(fighting(a)){a.encounter+=dt;const b=w.animals.find(b=>b.id===a.targetId);if(!b||b.state==='carried'||b.penId!==a.penId||a.encounter>10||a.energy<12){calm(a)}else {const d=distance(a.pos,b.pos),contact=r+info[b.species].radius*b.scale+.65;if(a.state==='flee'){if(a.timer<=0||d>14)calm(a)}else if(a.state==='alert'){a.heading=Math.atan2(b.pos.x-a.pos.x,b.pos.z-a.pos.z);if(a.timer<=0){a.state='chase';a.decision=0}}else if(a.state==='chase'){if(d<contact){a.state='attack';a.timer=1.15;a.hit=false;a.path=[]}else if(a.decision<=0){goal(a,b.pos);a.decision=.65}}else if(a.state==='attack'){a.heading=Math.atan2(b.pos.x-a.pos.x,b.pos.z-a.pos.z);if(a.timer<.62&&!a.hit){a.hit=true;if(d<contact+.5){b.energy=Math.max(5,b.energy-s.power*1.5);b.recoil=.6;a.energy-=4;w.conflictCount++;event(w,a.pos,`${s.name}与${info[b.species].name}发生冲突`,'fight');if(info[b.species].power<s.power*1.1)flee(w,b,a);else {releaseFood(w,b);b.state='alert';b.targetId=a.id;b.timer=.7;b.path=[]}}}if(a.timer<=0){if(a.encounter>6)calm(a);else {a.state='chase';a.decision=0}}}}}
 if(!fighting(a)&&a.cooldown<=0&&a.state!=='settle'&&a.decision<=0){a.decision=1.3+random(w);const foreign=near.filter(b=>b.id!==a.id&&b.species!==a.species&&b.state!=='carried'&&distance(a.pos,b.pos)<10).sort((b,c)=>distance(a.pos,b.pos)-distance(a.pos,c.pos))[0];if(foreign){const other=info[foreign.species];if((s.diet==='meat'||s.id==='hippo')&&random(w)<s.aggression*a.temper*.7){releaseFood(w,a);a.state='alert';a.targetId=foreign.id;a.timer=1.2;a.encounter=0;a.path=[]}else if(other.diet==='meat'&&other.power>s.power*1.5)flee(w,a,foreign)}}
 if(['rest','roam'].includes(a.state)&&a.hunger>42){const food=w.foods.find(f=>f.penId===a.penId&&f.diet===s.diet&&f.amount>1&&Object.keys(f.slots).length<3);if(food){let slot=0;while(Object.values(food.slots).includes(slot))slot++;const p=nearestFree({x:food.pos.x+Math.sin(slot*Math.PI*2/3)*(r+.8),z:food.pos.z+Math.cos(slot*Math.PI*2/3)*(r+.8)},pen,r,swimmer(a.species));if(p){releaseFood(w,a);food.slots[a.id]=slot;a.foodId=food.id;goal(a,p);if(a.path.length){a.state='seek';a.timer=45}else releaseFood(w,a)}}}
 if(a.state==='eat'){const f=w.foods.find(f=>f.id===a.foodId);a.speed=0;if(!f||f.amount<=0||a.hunger<12||a.timer<=0){releaseFood(w,a);a.state='rest';a.timer=3+random(w)*5}else {a.heading=Math.atan2(f.pos.x-a.pos.x,f.pos.z-a.pos.z);const amount=Math.min(f.amount,dt*1.7);f.amount-=amount;a.hunger=Math.max(0,a.hunger-amount*3.5);a.energy=Math.min(100,a.energy+dt)}}
 if(['rest','settle','display'].includes(a.state)){a.speed*=Math.exp(-dt*8);a.energy=Math.min(100,a.energy+dt*.2);if(a.timer<=0){if(a.species==='peacock'&&a.state!=='display'&&random(w)<.35){a.state='display';a.timer=8}else wander(w,a)}}
 if(['roam','seek','chase','flee','fly'].includes(a.state)){let next=a.path[0];if(next&&distance(a.pos,next)<.35){a.path.shift();next=a.path[0]}if(next){const desired=Math.atan2(next.x-a.pos.x,next.z-a.pos.z),turn=Math.atan2(Math.sin(desired-a.heading),Math.cos(desired-a.heading));a.heading+=Math.max(-dt*3,Math.min(dt*3,turn));const fast=['chase','flee'].includes(a.state)?2.6:a.state==='fly'?3:1;a.speed+=(s.speed*fast-a.speed)*(1-Math.exp(-dt*4));const dist=a.speed*dt*Math.max(.15,Math.cos(turn));let dx=Math.sin(a.heading)*dist,dz=Math.cos(a.heading)*dist;for(const b of near){if(b.id===a.id||b.state==='carried'||b.id===a.targetId)continue;const d=distance(a.pos,b.pos),space=r+info[b.species].radius*b.scale+.3;if(d>0&&d<space){dx+=(a.pos.x-b.pos.x)/d*(space-d)*dt*2;dz+=(a.pos.z-b.pos.z)/d*(space-d)*dt*2}}const pos={x:a.pos.x+dx,z:a.pos.z+dz};if(walkable(pos,pen,r,swimmer(a.species))){const moved=distance(pos,a.pos);a.pos=pos;a.gait+=moved/(s.stride*a.scale)*Math.PI*2}else {a.speed=0;if(a.decision<=0){const end=a.path.at(-1);if(end)goal(a,end);a.decision=1}}}else if(a.state==='seek'){a.state='eat';a.timer=22;a.speed=0}else if(a.state!=='chase'){a.state='rest';a.timer=2+random(w)*6;a.speed=0}if(a.timer<=0&&!fighting(a)){releaseFood(w,a);a.state='rest';a.timer=2;a.path=[]}}
 const flightHeight=a.species==='peacock'?1.5:a.species==='flamingo'?2.7:3.4
 a.altitude+=( (a.state==='fly'?flightHeight+Math.sin(a.phase*2)*.13:0)-a.altitude)*(1-Math.exp(-dt*2))
 }
 for(const k of w.keepers){k.phase+=dt;if(k.state==='walk'){const p=k.route[0];if(!p){k.state='feed';k.timer=2.4;continue}const d=distance(k.pos,p);k.heading=Math.atan2(p.x-k.pos.x,p.z-k.pos.z);if(d<.25)k.route.shift();else {const step=Math.min(d,dt*2.6);k.pos.x+=(p.x-k.pos.x)/d*step;k.pos.z+=(p.z-k.pos.z)/d*step}}else {k.timer-=dt;if(k.timer<=0){const pen=pens[k.penIndex],diets=[...new Set(w.animals.filter(a=>a.penId===pen.id).map(a=>info[a.species].diet))];diets.forEach((diet,i)=>{const existing=w.foods.find(f=>f.penId===pen.id&&f.diet===diet);if(existing){existing.amount=80;existing.age=0}else w.foods.push({id:`food-${w.elapsed}-${k.id}-${diet}`,penId:pen.id,diet,pos:pen.feeders[i%2],amount:80,age:0,slots:{}})});w.feedCount++;const old=pen.angle;k.penIndex=k.id*3+(k.penIndex-k.id*3+1)%3;const next=pens[k.penIndex];let delta=next.angle-old;if(delta<0)delta+=Math.PI*2;k.route=[roadPoint(old),...Array.from({length:Math.ceil(delta*10)},(_,i)=>roadPoint(old+delta*(i+1)/Math.ceil(delta*10))),next.gate];k.state='walk'}}}
 for(const f of w.foods)f.age+=dt;w.foods=w.foods.filter(f=>f.age<480);w.events=w.events.filter(e=>w.elapsed-e.time<12)
}
export function animalHeight(a:Animal){const w=waterAt(a.pos);return (w&&a.species==='hippo'?w.level-.6:terrainHeight(a.pos.x,a.pos.z))+a.altitude}
