import {Suspense,useEffect,useRef} from 'react'
import {Canvas,useFrame,useThree,type ThreeEvent} from '@react-three/fiber'
import {Html,OrbitControls,Sky,useProgress} from '@react-three/drei'
import {Camera,Group,MathUtils,MOUSE,Vector3} from 'three'
import type {OrbitControls as Controls} from 'three-stdlib'
import Landscape from './Landscape'
import {cameraMovement,focusAngle,movementCodes} from './camera'
import RiggedAnimal from './RiggedAnimal'
import {animalHeight,info,stepWorld,terrainHeight,type Animal,type Keeper,type Point,type ZooWorld} from './zoo'
export type CameraCommand={id:number;mode:'overview'|'focus'|'map'|'entrance';point?:Point;animalId?:string}
export type CameraSnapshot={x:number;z:number;tx:number;tz:number;distance:number}
type Props={world:ZooWorld;selected:string|null;command:CameraCommand;carrying:boolean;onAnimalDown:(id:string,e:PointerEvent)=>void;onFocus:(id:string)=>void;onReady:(camera:Camera,canvas:HTMLCanvasElement,controls:Controls)=>void;onCamera:(v:CameraSnapshot)=>void}
function CameraRig({world,command,carrying,onReady,onCamera}:Pick<Props,'world'|'command'|'carrying'|'onReady'|'onCamera'>){const ref=useRef<Controls>(null),{camera,gl,size}=useThree(),motion=useRef<{position:Vector3;target:Vector3;active:boolean}>({position:new Vector3(138,135,155),target:new Vector3(0,0,0),active:true}),tick=useRef(0),follow=useRef<string|null>(null),lastFocus=useRef(new Vector3()),pressed=useRef(new Set<string>())
 useEffect(()=>{if(ref.current)onReady(camera,gl.domElement,ref.current)},[camera,gl,onReady])
 useEffect(()=>{
  const down=(event:KeyboardEvent)=>{
   if(!movementCodes.has(event.code)||event.altKey||event.ctrlKey||event.metaKey||event.isComposing)return
   const target=event.target as HTMLElement|null
   if(target?.closest('input,textarea,select,[contenteditable="true"],.help'))return
   event.preventDefault();motion.current.active=false;follow.current=null
   const c=ref.current
   // 轻触按键也立即响应，长按再由每帧增量连续移动。
   if(c&&!pressed.current.has(event.code)){const delta=cameraMovement(new Set([event.code]),{x:c.target.x-camera.position.x,z:c.target.z-camera.position.z},1/60,camera.position.distanceTo(c.target));camera.position.x+=delta.x;camera.position.z+=delta.z;c.target.x+=delta.x;c.target.z+=delta.z}
   pressed.current.add(event.code)
  }
  const up=(event:KeyboardEvent)=>{pressed.current.delete(event.code)}
  const clear=()=>pressed.current.clear()
  window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',clear);document.addEventListener('visibilitychange',clear)
  return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',clear);document.removeEventListener('visibilitychange',clear);clear()}
 },[camera])
 useEffect(()=>{follow.current=command.mode==='focus'?(command.animalId??null):null;const a=world.animals.find(a=>a.id===command.animalId),p=command.point??a?.pos??{x:0,z:0},h=a?info[a.species].height:0;if(command.mode==='overview')motion.current={position:new Vector3(138,135,155),target:new Vector3(0,0,0),active:true};else if(command.mode==='entrance'){const distance=Math.max(43,29/(Math.tan(23*Math.PI/180)*size.width/size.height));motion.current={position:new Vector3(26,6+distance*.16,112+distance),target:new Vector3(26,6,112),active:true}}else if(command.mode==='focus'){const d=Math.max(4.2,h*2.2,(a?info[a.species].radius:1)*4/Math.min(1,size.width/size.height)),angle=a?focusAngle(a,d):Math.PI/3;lastFocus.current.set(p.x,0,p.z);motion.current={position:new Vector3(p.x+Math.sin(angle)*d,terrainHeight(p.x,p.z)+h*.8+d*.3,p.z+Math.cos(angle)*d),target:new Vector3(p.x,terrainHeight(p.x,p.z)+h*.55,p.z),active:true}}else {const delta=new Vector3(p.x-ref.current!.target.x,0,p.z-ref.current!.target.z);motion.current={position:camera.position.clone().add(delta),target:new Vector3(p.x,terrainHeight(p.x,p.z),p.z),active:true};if(camera.position.y>55)motion.current.position.set(p.x+20,36,p.z+27)}},[command,world,camera,size.width,size.height])
 useFrame((_,dt)=>{const c=ref.current;if(!c)return;const m=motion.current;const movement=cameraMovement(pressed.current,{x:c.target.x-camera.position.x,z:c.target.z-camera.position.z},dt,camera.position.distanceTo(c.target));camera.position.x+=movement.x;camera.position.z+=movement.z;c.target.x+=movement.x;c.target.z+=movement.z;if(follow.current){const a=world.animals.find(a=>a.id===follow.current);if(a){const next=new Vector3(a.pos.x,0,a.pos.z),delta=next.clone().sub(lastFocus.current);m.position.add(delta);m.target.add(delta);lastFocus.current.copy(next);m.active=true}}if(m.active){const t=1-Math.exp(-dt*4);camera.position.lerp(m.position,t);c.target.lerp(m.target,t);if(camera.position.distanceTo(m.position)<.04)m.active=false}camera.position.y=Math.max(camera.position.y,terrainHeight(camera.position.x,camera.position.z)+1.1);const tx=MathUtils.clamp(c.target.x,-140,140),tz=MathUtils.clamp(c.target.z,-115,145);camera.position.x+=tx-c.target.x;camera.position.z+=tz-c.target.z;c.target.x=tx;c.target.z=tz;c.update();tick.current+=dt;if(tick.current>.1){tick.current=0;onCamera({x:camera.position.x,z:camera.position.z,tx:c.target.x,tz:c.target.z,distance:camera.position.distanceTo(c.target)})}})
 return <OrbitControls ref={ref} makeDefault enabled enableDamping dampingFactor={.16} screenSpacePanning={false} zoomToCursor mouseButtons={{LEFT:carrying?undefined:MOUSE.ROTATE,MIDDLE:MOUSE.PAN,RIGHT:MOUSE.PAN}} minDistance={2} maxDistance={330} maxPolarAngle={Math.PI*.477} minPolarAngle={.14} onStart={()=>{motion.current.active=false;follow.current=null}} zoomSpeed={.85} panSpeed={1.05} rotateSpeed={.45}/>
}
function AnimalView({animal,selected,onDown,onFocus}:{animal:Animal;selected:boolean;onDown:Props['onAnimalDown'];onFocus:Props['onFocus']}){const ref=useRef<Group>(null),hover=useRef(false),label=useRef<HTMLDivElement>(null);useFrame(()=>{if(ref.current){ref.current.position.set(animal.pos.x,animalHeight(animal)+(animal.state==='carried'?2:0),animal.pos.z);ref.current.rotation.y=animal.heading}if(label.current)label.current.style.display=hover.current?'block':'none'});const s=info[animal.species];return <group ref={ref} onPointerDown={(e:ThreeEvent<PointerEvent>)=>{if(e.button!==0)return;e.stopPropagation();onDown(animal.id,e.nativeEvent)}} onDoubleClick={e=>{e.stopPropagation();onFocus(animal.id)}} onPointerOver={e=>{e.stopPropagation();hover.current=true;document.body.style.cursor='grab'}} onPointerOut={()=>{hover.current=false;document.body.style.cursor='auto'}}>
 <RiggedAnimal animal={animal}/>{selected&&<mesh rotation={[-Math.PI/2,0,0]} position={[0,.035,0]}><ringGeometry args={[s.radius*1.15,s.radius*1.15+.065,48]}/><meshBasicMaterial color={animal.state==='carried'?'#f5d38c':'#f4e4ac'} transparent opacity={.8} depthWrite={false}/></mesh>}
 <Html position={[0,s.height+.45,0]} center style={{pointerEvents:'none'}}><div ref={label} className="animal-label" style={{display:'none'}}>{s.name} · {animal.id.split('-').at(-1)}</div></Html>
 </group>}
function KeeperView({keeper}:{keeper:Keeper}){const ref=useRef<Group>(null),limbs=useRef<(Group|null)[]>([]);useFrame(()=>{if(ref.current){ref.current.position.set(keeper.pos.x,terrainHeight(keeper.pos.x,keeper.pos.z),keeper.pos.z);ref.current.rotation.y=keeper.heading}limbs.current.forEach((g,i)=>{if(g)g.rotation.x=keeper.state==='walk'?Math.sin(keeper.phase*7+(i%2)*Math.PI)*.4: i<2?0:-.8+Math.sin(keeper.phase*5)*.3})});return <group ref={ref}>
 <mesh position={[0,1.21,0]} castShadow><capsuleGeometry args={[.22,.43,4,8]}/><meshStandardMaterial color="#788260"/></mesh><mesh position={[0,1.75,0]} castShadow><sphereGeometry args={[.16,12,10]}/><meshStandardMaterial color="#b98d68"/></mesh><mesh position={[0,1.9,0]} castShadow><cylinderGeometry args={[.22,.29,.1,12]}/><meshStandardMaterial color="#b5a77f"/></mesh>
 {[0,1,2,3].map(i=><group key={i} ref={g=>{limbs.current[i]=g}} position={[(i%2?1:-1)*(i<2?.12:.26),i<2?.94:1.4,0]}><mesh position={[0,i<2?-.37:-.24,0]} castShadow><capsuleGeometry args={[i<2?.085:.065,i<2?.58:.35,4,8]}/><meshStandardMaterial color={i<2?'#5b6554':'#a58d69'}/></mesh>{i<2&&<mesh position={[0,-.84,.07]}><boxGeometry args={[.18,.12,.28]}/><meshStandardMaterial color="#403e36"/></mesh>}</group>)}<mesh position={[.36,.7,0]} castShadow><cylinderGeometry args={[.2,.15,.3,10]}/><meshStandardMaterial color="#888a7b" metalness={.5} roughness={.5}/></mesh></group>}
function Simulation({world}:{world:ZooWorld}){const accumulator=useRef(0);useFrame((_,dt)=>{accumulator.current+=Math.min(dt,.15);while(accumulator.current>=1/30){stepWorld(world,1/30);accumulator.current-=1/30}});return null}
function FoodView({world}:{world:ZooWorld}){const ref=useRef<Group>(null);useFrame(()=>{ref.current?.children.forEach((child,i)=>{const f=world.foods[i];child.visible=!!f&&f.amount>0;if(f){child.position.set(f.pos.x,terrainHeight(f.pos.x,f.pos.z)+.2,f.pos.z);child.scale.setScalar(Math.max(.15,Math.min(1,f.amount/40)))}})});return <group ref={ref}>{Array.from({length:36},(_,i)=><group key={i}>{[0,1,2,3].map(j=><mesh key={j} position={[Math.cos(j*2.4)*.3,.07,Math.sin(j*2.4)*.3]}><sphereGeometry args={[.22,8,6]}/><meshStandardMaterial color={['#af9c60','#839350','#a17a5c','#aab66f'][j]}/></mesh>)}</group>)}</group>}
function Loader(){const {progress}=useProgress();return <Html center><div className="loading">正在准备园区 <b>{Math.round(progress)}%</b></div></Html>}
export default function ZooScene(props:Props){return <Canvas shadows dpr={[1,1.6]} camera={{position:[138,135,155],fov:46,near:.1,far:900}} gl={{antialias:true,powerPreference:'high-performance'}}><color attach="background" args={['#c6d6d5']}/><fog attach="fog" args={['#c6d6d5',220,620]}/><Sky distance={450000} sunPosition={[80,100,45]} turbidity={5} rayleigh={.8}/><hemisphereLight args={['#d9e5ed','#777257',2.1]}/><directionalLight position={[70,110,55]} intensity={3} color="#fff0d1" castShadow shadow-mapSize={[2048,2048]} shadow-camera-left={-125} shadow-camera-right={125} shadow-camera-top={125} shadow-camera-bottom={-125} shadow-camera-far={320} shadow-normalBias={.08}/><CameraRig {...props}/><Landscape/><Simulation world={props.world}/><FoodView world={props.world}/>{props.world.keepers.map(k=><KeeperView key={k.id} keeper={k}/>)}<Suspense fallback={<Loader/>}>{props.world.animals.map(a=><AnimalView key={a.id} animal={a} selected={props.selected===a.id} onDown={props.onAnimalDown} onFocus={props.onFocus}/>)}</Suspense></Canvas>}
